# Generated by Django 6.1.1 on 2026-09-24 22:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_number', models.PositiveSmallIntegerField(default=1)),
                ('total_time_seconds', models.FloatField(default=0.0)),
                ('rest_time_seconds', models.FloatField(default=0.0)),
                ('effort_percentage', models.FloatField(default=0.0, help_text='Ratio of measured swim speed vs personal best speed (or baseline).')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LapSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.PositiveSmallIntegerField(default=1)),
                ('split_time_seconds', models.FloatField(help_text='Duration of this specific lap split.')),
                ('stroke_count', models.PositiveSmallIntegerField(default=0)),
                ('stroke_rate', models.FloatField(default=0.0, help_text='Stroke cadence in strokes per minute.')),
                ('dps', models.FloatField(default=0.0, help_text='Distance per stroke in meters.')),
                ('breakout_distance_m', models.FloatField(default=0.0, help_text='Distance from wall at breakout in meters.')),
                ('turn_time_seconds', models.FloatField(blank=True, help_text='Turn window time (e.g., 5m in to 5m out).', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('repetition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='tracker.repetition')),
            ],
            options={
                'ordering': ['lap_number'],
            },
        ),
        migrations.CreateModel(
            name='SwimmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_velocity', models.FloatField(default=1.3, help_text='Baseline aerobic threshold speed in m/s used for default effort scoring.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swimmer_profile', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swimmers', to='tracker.team')),
            ],
        ),
        migrations.AddField(
            model_name='repetition',
            name='swimmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetitions', to='tracker.swimmerprofile'),
        ),
        migrations.CreateModel(
            name='HardwareTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(help_text='Hardware MAC address, UWB ID, or laser-etched ID string.', max_length=32, unique=True)),
                ('battery_percentage', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('firmware_version', models.CharField(default='1.0.0', max_length=32)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('active_swimmer', models.OneToOneField(blank=True, help_text='Currently assigned swimmer for deck practice session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_tag', to='tracker.swimmerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_course', models.CharField(choices=[('SCY_25Y', 'Short Course Yards (25yd)'), ('SCM_25M', 'Short Course Meters (25m)'), ('LCM_50M', 'Long Course Meters (50m)')], default='SCY_25Y', max_length=10)),
                ('mode', models.CharField(choices=[('FREE_SWIM', 'Free-Swim Capture'), ('STRUCTURED', 'Pre-Programmed Sets')], default='FREE_SWIM', max_length=12)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active on Deck'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coached_sessions', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tracker.team')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_order', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(default='Main Set', max_length=120)),
                ('stroke', models.CharField(choices=[('FREESTYLE', 'Freestyle'), ('BACKSTROKE', 'Backstroke'), ('BREASTSTROKE', 'Breaststroke'), ('BUTTERFLY', 'Butterfly'), ('IM', 'Individual Medley'), ('CHOICE', 'Choice')], default='FREESTYLE', max_length=20)),
                ('target_distance', models.PositiveIntegerField(default=100, help_text='Target distance in pool units (e.g. 50, 100)')),
                ('target_interval_sec', models.PositiveIntegerField(blank=True, help_text='Send-off interval in seconds (e.g. 90 for 1:30)', null=True)),
                ('target_reps', models.PositiveSmallIntegerField(default=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='tracker.practicesession')),
            ],
            options={
                'ordering': ['set_order'],
            },
        ),
        migrations.AddField(
            model_name='repetition',
            name='workout_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetitions', to='tracker.workoutset'),
        ),
        migrations.CreateModel(
            name='PersonalBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke', models.CharField(choices=[('FREESTYLE', 'Freestyle'), ('BACKSTROKE', 'Backstroke'), ('BREASTSTROKE', 'Breaststroke'), ('BUTTERFLY', 'Butterfly'), ('IM', 'Individual Medley'), ('CHOICE', 'Choice')], max_length=20)),
                ('distance_units', models.CharField(choices=[('SCY_25Y', 'Short Course Yards (25yd)'), ('SCM_25M', 'Short Course Meters (25m)'), ('LCM_50M', 'Long Course Meters (50m)')], max_length=10)),
                ('distance', models.PositiveIntegerField(help_text='Distance (e.g. 50, 100, 200)')),
                ('time_seconds', models.FloatField(help_text='PB time recorded in seconds (e.g. 23.45)')),
                ('achieved_at', models.DateField(auto_now=True)),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_bests', to='tracker.swimmerprofile')),
            ],
            options={
                'unique_together': {('swimmer', 'stroke', 'distance_units', 'distance')},
            },
        ),
    ]
