# Generated by Django 6.1.1 on 2026-09-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_self_registration', models.BooleanField(default=True, help_text='Allow swimmers to self-register accounts.')),
                ('team_leaderboard_visible', models.BooleanField(default=False, help_text="Allow swimmers to view teammates' metrics and historical leaderboards.")),
                ('default_pool_course', models.CharField(choices=[('SCY_25Y', 'Short Course Yards (25yd)'), ('SCM_25M', 'Short Course Meters (25m)'), ('LCM_50M', 'Long Course Meters (50m)')], default='SCY_25Y', help_text='Default pool standard for new practice sessions.', max_length=10)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
