# Generated by Django 6.1.1 on 2026-09-26 17:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_systemconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaneAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_number', models.PositiveSmallIntegerField(help_text='Assigned pool lane number (1 to 8)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('staged_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane_assignments', to='tracker.practicesession')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lane_assignments', to='tracker.swimmerprofile')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lane_assignments', to='tracker.hardwaretag')),
            ],
            options={
                'ordering': ['lane_number', 'staged_at'],
                'unique_together': {('session', 'swimmer')},
            },
        ),
    ]
