# Generated by Django 6.1.1 on 2026-09-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_laneassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaretag',
            name='rssi',
            field=models.IntegerField(default=-65, help_text='Signal strength indicator in dBm (e.g., -60 to -90 dBm).'),
        ),
    ]
