# Generated by Django 6.1.1 on 2026-09-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_hardwaretag_rssi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laneassignment',
            options={'ordering': ['lane_number', 'order_in_lane', 'staged_at']},
        ),
        migrations.AddField(
            model_name='laneassignment',
            name='order_in_lane',
            field=models.PositiveSmallIntegerField(default=1, help_text='Position order in lane (1 = lead-off swimmer, 2 = second, etc.)'),
        ),
    ]
